name: WakaTime (Languages Only)

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Update README with WakaTime stats (languages only)
        uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

          SECTION_NAME: waka
          PUSH_BRANCH_NAME: main
          COMMIT_SINGLE: "True"
          COMMIT_MESSAGE: "chore: update waka stats"

          SHOW_LANGUAGE: "True"

          SHOW_OS: "False"
          SHOW_PROJECTS: "False"
          SHOW_EDITORS: "False"
          SHOW_TIMEZONE: "False"
          SHOW_COMMIT: "False"
          SHOW_LINES_OF_CODE: "False"
          SHOW_LANGUAGE_PER_REPO: "False"
          SHOW_LOC_CHART: "False"
          SHOW_DAYS_OF_WEEK: "False"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_SHORT_INFO: "False"
          SHOW_UPDATED_DATE: "False"
          SHOW_TOTAL_CODE_TIME: "False"

          SYMBOL_VERSION: "1"
